Update php77.yml

diff --git a/.github/workflows/php77.yml b/.github/workflows/php77.yml
--- a/.github/workflows/php77.yml
+++ b/.github/workflows/php77.yml
@@ -11,14 +11,25 @@ permissions:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    - name: List files in current directory
+      run: ls -al
+
+    - name: Debug - List all directories and files
+      run: find . -type f -print
 
     - name: Validate composer.json and composer.lock
-      run: composer validate --strict
+      run: |
+        if [ ! -f composer.json ]; then
+          echo "composer.json not found in the root directory."
+          exit 1
+        fi
+        composer validate --strict
 
     - name: Cache Composer packages
       id: composer-cache
@@ -32,8 +43,6 @@ jobs:
     - name: Install dependencies
       run: composer install --prefer-dist --no-progress
 
-    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
-    # Docs: https://getcomposer.org/doc/articles/scripts.md
-
+    # Uncomment and configure this step if you have a test script in composer.json
     # - name: Run test suite
     #   run: composer run-script test
